# Generated by Django 6.0.6 on 2026-07-07 02:30

import discord_tts.voices.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('guild_id', models.PositiveBigIntegerField()),
                ('audio_source', models.FileField(null=True, upload_to=discord_tts.voices.models.voice_audio_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'oga', 'm4a', 'aac', 'wma', 'opus', 'flac', 'alac'])])),
                ('processed_safetensor', models.FileField(blank=True, null=True, upload_to=discord_tts.voices.models.voice_safetensor_upload_to)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='exclusive_voices', to='common.discordaccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'guild_id'), name='unique_voice_name_per_guild')],
            },
        ),
    ]
