# Generated by Django 6.0.6 on 2026-07-07 02:30

from django.db import migrations
from discord_tts.voices.db_starter import add_default_voices


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_voices),
    ]
