# Generated by Django 6.0.6 on 2026-07-05 23:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0002_auto_20260703_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='audio_source',
            field=models.FileField(null=True, upload_to='voices/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav', 'aiff', 'aif', 'au', 'snd', 'raw', 'paf', 'svx', 'nist', 'sph', 'voc', 'ircam', 'sf', 'w64', 'mat', 'pvf', 'xi', 'htk', 'sds', 'avr', 'sd2', 'flac', 'caf', 'wve', 'ogg', 'oga', 'mpc', 'rf64', 'mp3'])]),
        ),
        migrations.AlterField(
            model_name='voice',
            name='processed_safetensor',
            field=models.FileField(blank=True, null=True, upload_to='safetensors/'),
        ),
    ]
