# Generated by Django 6.0.6 on 2026-07-06 00:20

import discord_tts.voices.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0003_alter_voice_audio_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='audio_source',
            field=models.FileField(null=True, upload_to=discord_tts.voices.models.voice_audio_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'oga', 'm4a', 'aac', 'wma', 'opus', 'flac', 'alac'])]),
        ),
        migrations.AlterField(
            model_name='voice',
            name='processed_safetensor',
            field=models.FileField(blank=True, null=True, upload_to=discord_tts.voices.models.voice_safetensor_upload_to),
        ),
        migrations.AddConstraint(
            model_name='voice',
            constraint=models.UniqueConstraint(fields=('name', 'guild_id'), name='unique_voice_name_per_guild'),
        ),
    ]
