# Generated by Django 6.0.6 on 2026-07-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('voices', '0004_alter_voice_audio_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='exclusive_voices', to='common.discordaccount'),
        ),
    ]
