# Generated by Django 6.0.6 on 2026-07-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.PositiveBigIntegerField(db_index=True, unique=True)),
            ],
        ),
    ]
