# Generated by Django 6.0.6 on 2026-07-07 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('voices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminGuildPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.BigIntegerField()),
                ('introduce_speaker', models.BooleanField(null=True)),
                ('speak_while_muted', models.BooleanField(null=True)),
                ('echo_say_command', models.BooleanField(null=True)),
            ],
            options={
                'verbose_name': 'Guild Admin Preference',
                'verbose_name_plural': 'Guild Admin Preferences',
            },
        ),
        migrations.CreateModel(
            name='UserGuildPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.BigIntegerField()),
                ('introduce_speaker', models.BooleanField(default=False)),
                ('speak_while_muted', models.BooleanField(default=True)),
                ('echo_say_command', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.discordaccount')),
                ('voice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voices.voice')),
            ],
            options={
                'verbose_name': 'User Admin Preference',
                'verbose_name_plural': 'User Admin Preferences',
                'constraints': [models.UniqueConstraint(fields=('account_id', 'guild_id'), name='unique_user_per_guild')],
            },
        ),
    ]
