# Generated by Django 6.0.6 on 2026-07-06 01:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
        ('voices', '0004_alter_voice_audio_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userguildpreferences',
            constraint=models.UniqueConstraint(fields=('discord_id', 'guild_id'), name='unique_user_per_guild'),
        ),
    ]
