# Generated by Django 6.0.6 on 2026-09-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('preferences', '0001_initial'),
        ('voices', '0002_auto_20260706_2130'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userguildpreferences',
            name='unique_user_per_guild',
        ),
        migrations.AddIndex(
            model_name='userguildpreferences',
            index=models.Index(fields=['account', 'guild_id'], name='user_guild_pref_acc_guild_idx'),
        ),
        migrations.AddConstraint(
            model_name='userguildpreferences',
            constraint=models.UniqueConstraint(fields=('account', 'guild_id'), name='unique_user_per_guild'),
        ),
    ]
