# Generated by Django 6.0.6 on 2026-07-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminGuildPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.BigIntegerField()),
                ('introduce_speaker', models.BooleanField(null=True)),
                ('speak_while_muted', models.BooleanField(null=True)),
                ('echo_say_command', models.BooleanField(null=True)),
            ],
        ),
    ]
