# Generated by Django 6.0.6 on 2026-07-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('guild_id', models.PositiveBigIntegerField()),
                ('audio_source', models.FileField(upload_to='raw-voices/')),
                ('processed_safetensor', models.FileField(blank=True, null=True, upload_to='voices/')),
            ],
        ),
    ]
