# Generated by Django 6.0.6 on 2026-07-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='audio_source',
            field=models.FileField(upload_to='raw-voices/'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='processed_safetensor',
            field=models.FileField(blank=True, null=True, upload_to='voices/'),
        ),
    ]
