# Generated by Django 6.0.6 on 2026-07-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUserProfile',
            fields=[
                ('discord_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('introduce_speaker', models.BooleanField(default=False)),
            ],
        ),
    ]
