# Generated by Django 6.0.6 on 2026-07-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('discord_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('guild_id', models.BigIntegerField()),
                ('introduce_speaker', models.BooleanField(default=False)),
            ],
        ),
    ]
